try(renv::activate())
args = commandArgs(trailingOnly=TRUE)
library(RWeka)
library(NoiseFiltersR)
library(kknn)
library(readr)

dataset <- paste("NoisyDatasets/", args[1], sep = "")
# df <- read.arff(dataset)
df <- read_csv(dataset, show_col_types = FALSE)  


# HARF algorithm
# set.seed(1)
df$class <- factor(df$class)
# try(out <- GE(class~., data = df, k=5))
# try(out1 <- GE(class~., data = df, k=7))
# try(out2 <- GE(class~., data = df, k=9))
try(out3 <- GE(class~., data = df, k=3))
try(out4 <- GE(class~., data = df, k=11))
output_dataset <- paste("NoisyDatasetsAfterFilters/GE-5/", args[1], sep = "")
output_dataset1 <- paste("NoisyDatasetsAfterFilters/GE-7/", args[1], sep = "")
output_dataset2 <- paste("NoisyDatasetsAfterFilters/GE-9/", args[1], sep = "")
output_dataset3 <- paste("NoisyDatasetsAfterFilters/GE-3/", args[1], sep = "")
output_dataset4 <- paste("NoisyDatasetsAfterFilters/GE-11/", args[1], sep = "")
# write.arff(out$cleanData, file = output_dataset)
# try(write_csv(out$cleanData, file = output_dataset))
# try(write_csv(out1$cleanData, file = output_dataset1))
# try(write_csv(out2$cleanData, file = output_dataset2))
try(write_csv(out3$cleanData, file = output_dataset3))
try(write_csv(out4$cleanData, file = output_dataset4))
