try(renv::activate())
args = commandArgs(trailingOnly=TRUE)
library(RWeka)
library(NoiseFiltersR)
library(kknn)
library(readr)

dataset <- paste("NoisyDatasets/", args[1], sep = "")
# df <- read.arff(dataset)
df <- read_csv(dataset, show_col_types = FALSE)  


# HARF algorithm
# set.seed(1)
df$class <- factor(df$class)
try(out <- ORBoostFilter(class~., data = df, d = 11))
try(out1 <- ORBoostFilter(class~., data = df, d = 3))
try(out2 <- ORBoostFilter(class~., data = df, d = 7))
try(out3 <- ORBoostFilter(class~., data = df, d = 15))
try(out4 <- ORBoostFilter(class~., data = df, d = 19))
output_dataset <- paste("NoisyDatasetsAfterFilters/ORBoost-11/", args[1], sep = "")
output_dataset1 <- paste("NoisyDatasetsAfterFilters/ORBoost-3/", args[1], sep = "")
output_dataset2 <- paste("NoisyDatasetsAfterFilters/ORBoost-7/", args[1], sep = "")
output_dataset3 <- paste("NoisyDatasetsAfterFilters/ORBoost-15/", args[1], sep = "")
output_dataset4 <- paste("NoisyDatasetsAfterFilters/ORBoost-19/", args[1], sep = "")
# write.arff(out$cleanData, file = output_dataset)
try(write_csv(out$cleanData, file = output_dataset))
try(write_csv(out1$cleanData, file = output_dataset1))
try(write_csv(out2$cleanData, file = output_dataset2))
try(write_csv(out3$cleanData, file = output_dataset3))
try(write_csv(out4$cleanData, file = output_dataset4))
